### ISSUE TITLE
Logo and Demo gif don't show on PyPI

### ISSUE THREAD

**Issue by RackReaver** [RackReaver/FinPack#49]
I know the issue is because they are linked in the README.md as relative links which can't be understood by PyPI. I am not sure if switching them to non-relative will fix it or if a script needs to be run before publishing to PyPI to replace the links.

Might require some research into how other projects are handling this issue.

branch-name `docs/49-logo-demo-fix-pypi`
commit message example `#49 - Fix logo and demo link`

**Comment by Nate1729** [comment]
Does [this](https://stackoverflow.com/questions/41983209/how-do-i-add-images-to-a-pypi-readme-that-works-on-github/46875147) answer your question?

**Comment by RackReaver** [comment]
> Does [this](https://stackoverflow.com/questions/41983209/how-do-i-add-images-to-a-pypi-readme-that-works-on-github/46875147) answer your question?

Thats what I assumed would be required, I wish there was a way to provide a backup url or a way to change the source when generating the build for PyPI, I guess there are real limitations to markdown.
